// =============================================================================
// SOVEREIGN - Game Constants
// =============================================================================

// -----------------------------------------------------------------------------
// Helper Types
// -----------------------------------------------------------------------------

export type ResourceCost = {
  readonly ore?: number;
  readonly provisions?: number;
  readonly gold?: number;
  readonly lumber?: number;
  readonly mana?: number;
  readonly timeSeconds: number;
};

export type UnitType =
  | "INFANTRY"
  | "ARCHER"
  | "HEAVY_INFANTRY"
  | "WARDEN"
  | "CARAVAN"
  | "SCOUT"
  | "CAVALRY";

export type DefenseStructureType =
  | "WALLS"
  | "GUARD_TOWER"
  | "WATCH_TOWER"
  | "BALLISTA";

// -----------------------------------------------------------------------------
// 1. Tick & Season Timing
// -----------------------------------------------------------------------------

export const TICK_INTERVAL_MS = 30_000;

export const SEASON_DURATION_DAYS: number =
  typeof process !== "undefined" && process.env.SEASON_DURATION_DAYS
    ? Number(process.env.SEASON_DURATION_DAYS)
    : 14;

// -----------------------------------------------------------------------------
// 3. Resource Production Rates (per tick)
// -----------------------------------------------------------------------------

export const BASE_ORE_PER_TICK = 5;
export const BASE_PROVISIONS_PER_TICK = 5;   // was 8 — provisions reserved for ops
export const BASE_GOLD_PER_TICK = 0;          // was 2 — gold is now raid/trade only
export const BASE_LUMBER_PER_TICK = 0;        // only generated by Sawmill
export const BASE_MANA_PER_TICK = 0;

// -----------------------------------------------------------------------------
// 4. Mine Level Multipliers
// -----------------------------------------------------------------------------

export const MINE_LEVEL_MULTIPLIERS = {
  1: 1.0,
  2: 1.2,
  3: 1.4,
  4: 1.65,
  5: 2.0,
  6: 2.4,
  7: 2.85,
  8: 3.4,
} as const;

// -----------------------------------------------------------------------------
// 4b. Sawmill Constants
// -----------------------------------------------------------------------------

export const SAWMILL_BASE_PER_TICK = 4;

export const SAWMILL_LEVEL_MULTIPLIERS = {
  1: 1.0,
  2: 1.3,
  3: 1.6,
  4: 2.0,
  5: 2.5,
  6: 3.0,
  7: 3.6,
  8: 4.3,
} as const;

export const SAWMILL_UPGRADE_COSTS = {
  2: { lumber: 400, ore: 200, timeSeconds: 8 * 60 } as ResourceCost,
  3: { lumber: 1000, ore: 500, timeSeconds: 20 * 60 } as ResourceCost,
  4: { lumber: 2500, ore: 1200, timeSeconds: 45 * 60 } as ResourceCost,
  5: { lumber: 5000, ore: 2500, timeSeconds: 90 * 60 } as ResourceCost,
  6: { lumber: 10000, ore: 5000, timeSeconds: 180 * 60 } as ResourceCost,
  7: { lumber: 18000, ore: 9000, timeSeconds: 300 * 60 } as ResourceCost,
  8: { lumber: 30000, ore: 15000, timeSeconds: 360 * 60 } as ResourceCost,
} as const;

// -----------------------------------------------------------------------------
// 4c. Barracks Upgrades (training speed)
// -----------------------------------------------------------------------------

export const BARRACKS_LEVEL_TRAINING_MULTIPLIERS = {
  1: 1.0, 2: 0.85, 3: 0.70, 4: 0.55, 5: 0.40,
} as const;

export const BARRACKS_UPGRADE_COSTS = {
  2: { ore: 300, lumber: 400, timeSeconds: 10 * 60 } as ResourceCost,
  3: { ore: 800, lumber: 1000, timeSeconds: 25 * 60 } as ResourceCost,
  4: { ore: 2000, lumber: 2500, timeSeconds: 60 * 60 } as ResourceCost,
  5: { ore: 5000, lumber: 6000, timeSeconds: 120 * 60 } as ResourceCost,
} as const;

// -----------------------------------------------------------------------------
// 4d. Farm Upgrades (provisions production)
// -----------------------------------------------------------------------------

export const FARM_LEVEL_MULTIPLIERS = {
  1: 1.0, 2: 1.3, 3: 1.6, 4: 2.0, 5: 2.5,
} as const;

export const FARM_UPGRADE_COSTS = {
  2: { lumber: 300, ore: 150, timeSeconds: 8 * 60 } as ResourceCost,
  3: { lumber: 800, ore: 400, timeSeconds: 20 * 60 } as ResourceCost,
  4: { lumber: 2000, ore: 1000, timeSeconds: 45 * 60 } as ResourceCost,
  5: { lumber: 5000, ore: 2500, timeSeconds: 90 * 60 } as ResourceCost,
} as const;

// -----------------------------------------------------------------------------
// 4e. Unit Upkeep (provisions per tick per unit)
// -----------------------------------------------------------------------------

export const UNIT_UPKEEP_PER_TICK = {
  INFANTRY: 0.5, ARCHER: 0.5, HEAVY_INFANTRY: 0.8,
  WARDEN: 0.3, CARAVAN: 1.0, SCOUT: 0.3, CAVALRY: 1.5,
} as const;

// -----------------------------------------------------------------------------
// 5. Crop Mastery Multipliers
// -----------------------------------------------------------------------------

export const CROP_MASTERY_MULTIPLIERS = {
  0: 1.0,
  1: 1.3,
  2: 1.6,
  3: 2.0,
  4: 2.5,
  5: 3.0,
} as const;

// -----------------------------------------------------------------------------
// 5b. Forestry Multipliers (boosts Sawmill output)
// -----------------------------------------------------------------------------

export const FORESTRY_MULTIPLIERS = {
  0: 1.0,
  1: 1.2,
  2: 1.4,
  3: 1.7,
  4: 2.0,
  5: 2.5,
} as const;

export const FORESTRY_COSTS = {
  1: { lumber: 200, timeSeconds: 3 * 60 } as ResourceCost,
  2: { lumber: 450, timeSeconds: 6 * 60 } as ResourceCost,
  3: { lumber: 900, timeSeconds: 12 * 60 } as ResourceCost,
  4: { lumber: 1800, timeSeconds: 24 * 60 } as ResourceCost,
  5: { lumber: 3200, timeSeconds: 40 * 60 } as ResourceCost,
} as const;

// -----------------------------------------------------------------------------
// 6. War Tech Costs
//    Tracks: BALLISTICS, DEFENSE_TRACK, STRATEGY (levels 1-5)
//    Ore only, slightly cheaper/faster to reduce idle time
// -----------------------------------------------------------------------------

const WAR_TECH_LEVEL_COSTS: Record<number, ResourceCost> = {
  1: { ore: 150, timeSeconds: 2 * 60 },
  2: { ore: 350, timeSeconds: 5 * 60 },
  3: { ore: 700, timeSeconds: 10 * 60 },
  4: { ore: 1400, timeSeconds: 20 * 60 },
  5: { ore: 2800, timeSeconds: 35 * 60 },
} as const;

export const WAR_TECH_COSTS = {
  BALLISTICS: { ...WAR_TECH_LEVEL_COSTS },
  DEFENSE_TRACK: { ...WAR_TECH_LEVEL_COSTS },
  STRATEGY: { ...WAR_TECH_LEVEL_COSTS },
} as const;

// -----------------------------------------------------------------------------
// 7. Agriculture Costs (provisions only)
// -----------------------------------------------------------------------------

export const AGRICULTURE_COSTS = {
  CROP_MASTERY: {
    1: { provisions: 200, timeSeconds: 3 * 60 },
    2: { provisions: 450, timeSeconds: 6 * 60 },
    3: { provisions: 900, timeSeconds: 12 * 60 },
    4: { provisions: 1800, timeSeconds: 24 * 60 },
    5: { provisions: 3200, timeSeconds: 40 * 60 },
  },
  ANIMAL_HUSBANDRY: {
    1: { provisions: 250, timeSeconds: 4 * 60 },
    2: { provisions: 500, timeSeconds: 8 * 60 },
    3: { provisions: 1000, timeSeconds: 14 * 60 },
    4: { provisions: 2000, timeSeconds: 25 * 60 },
    5: { provisions: 3500, timeSeconds: 40 * 60 },
  },
} as const;

// -----------------------------------------------------------------------------
// 8. Mine Upgrade Costs (ore + lumber)
// -----------------------------------------------------------------------------

export const MINE_UPGRADE_COSTS = {
  2: { ore: 400, lumber: 200, timeSeconds: 10 * 60 } as ResourceCost,
  3: { ore: 1000, lumber: 500, timeSeconds: 25 * 60 } as ResourceCost,
  4: { ore: 2500, lumber: 1200, timeSeconds: 60 * 60 } as ResourceCost,
  5: { ore: 5000, lumber: 2500, timeSeconds: 120 * 60 } as ResourceCost,
  6: { ore: 10000, lumber: 5000, timeSeconds: 180 * 60 } as ResourceCost,
  7: { ore: 18000, lumber: 9000, timeSeconds: 300 * 60 } as ResourceCost,
  8: { ore: 30000, lumber: 15000, timeSeconds: 360 * 60 } as ResourceCost,
} as const;

// -----------------------------------------------------------------------------
// 9. Citadel Upgrade Costs (multi-resource, gold reduced)
// -----------------------------------------------------------------------------

export const CITADEL_UPGRADE_COSTS = {
  2: { gold: 500, lumber: 800, ore: 400, timeSeconds: 30 * 60 } as ResourceCost,
  3: { gold: 1500, lumber: 2000, ore: 1000, timeSeconds: 90 * 60 } as ResourceCost,
  4: { gold: 4000, lumber: 5000, ore: 2500, timeSeconds: 180 * 60 } as ResourceCost,
} as const;

// -----------------------------------------------------------------------------
// 10. Scout Cap by Citadel Level
// -----------------------------------------------------------------------------

export const SCOUT_CAP_BY_CITADEL = {
  1: 1,
  2: 2,
  3: 3,
  4: 4,
} as const;

// -----------------------------------------------------------------------------
// 11. Frontier Cap by Citadel Level
// -----------------------------------------------------------------------------

export const FRONTIER_CAP_BY_CITADEL = {
  1: 0,
  2: 1,
  3: 2,
  4: 3,
} as const;

// -----------------------------------------------------------------------------
// 12. Unit Training Costs
//     Ore + provisions primary, gold for premium only
// -----------------------------------------------------------------------------

export const UNIT_TRAINING_COSTS = {
  INFANTRY: {
    ore: 15,
    provisions: 10,
    gold: 0,
    timeSeconds: 75,
    requires: null,
  },
  ARCHER: {
    ore: 25,
    provisions: 12,
    gold: 0,
    timeSeconds: 112,
    requires: { BALLISTICS: 1 },
  },
  HEAVY_INFANTRY: {
    ore: 50,
    provisions: 20,
    gold: 0,
    timeSeconds: 225,
    requires: { totalWar: 3, mine: 2 },
  },
  WARDEN: {
    ore: 35,
    provisions: 25,
    gold: 0,
    timeSeconds: 150,
    requires: { DEFENSE_TRACK: 2 },
  },
  CARAVAN: {
    ore: 10,
    provisions: 40,
    gold: 0,
    timeSeconds: 112,
    requires: { ANIMAL_HUSBANDRY: 2 },
  },
  SCOUT: {
    ore: 15,
    provisions: 15,
    gold: 0,
    timeSeconds: 150,
    requires: { STRATEGY: 1 },
  },
  CAVALRY: {
    ore: 60,
    provisions: 35,
    gold: 15,
    timeSeconds: 300,
    requires: { totalWar: 5, ANIMAL_HUSBANDRY: 3 },
  },
} as const;

// -----------------------------------------------------------------------------
// 13. Unit Stats
//     attack, defense, speed (tiles per minute), carryCapacity
// -----------------------------------------------------------------------------

export const UNIT_STATS = {
  INFANTRY: { attack: 9, defense: 7, speed: 0.5, carryCapacity: 0, provisionPerTile: 2 },
  ARCHER: { attack: 5, defense: 5, speed: 0.5, carryCapacity: 0, provisionPerTile: 2 },
  HEAVY_INFANTRY: { attack: 12, defense: 15, speed: 0.3, carryCapacity: 0, provisionPerTile: 3 },
  WARDEN: { attack: 3, defense: 25, speed: 0.1, carryCapacity: 0, provisionPerTile: 1 },
  CARAVAN: { attack: 0, defense: 2, speed: 0.4, carryCapacity: 200, provisionPerTile: 4 },
  SCOUT: { attack: 2, defense: 2, speed: 2.0, carryCapacity: 0, provisionPerTile: 1 },
  CAVALRY: { attack: 20, defense: 10, speed: 1.0, carryCapacity: 0, provisionPerTile: 5 },
} as const;

// -----------------------------------------------------------------------------
// PvP Constants
// -----------------------------------------------------------------------------

export const PVP_LOOT_PERCENT = 0.15;
export const PROTECTION_DURATION_MS = 24 * 60 * 60 * 1000;

// -----------------------------------------------------------------------------
// Combat Structure Constants (used by phased combat)
// -----------------------------------------------------------------------------

export const WALL_HP_PER_LEVEL = 100
export const GUARD_TOWER_DAMAGE_PER_LEVEL = 20
export const CAVALRY_CHARGE_MULTIPLIER = 2.0

// -----------------------------------------------------------------------------
// 14. Combat Triangle
//     Damage multiplier when attacker engages defender.
//     Values > 1.0 = attacker has advantage.
//     Values < 1.0 = attacker has disadvantage (defender takes less damage).
// -----------------------------------------------------------------------------

export const COMBAT_TRIANGLE: Record<string, Record<string, number>> = {
  CAVALRY: {
    ARCHER: 1.25,
    INFANTRY: 0.8,
    HEAVY_INFANTRY: 0.75,
  },
  ARCHER: {
    INFANTRY: 1.25,
    CAVALRY: 0.8,
  },
  INFANTRY: {
    CAVALRY: 1.25,
    ARCHER: 0.8,
  },
  HEAVY_INFANTRY: {
    CAVALRY: 1.18, // 0.85 damage taken -> 1/0.85 ~ 1.18 effective multiplier
  },
} as const;

// -----------------------------------------------------------------------------
// 15. Defense Structure Bonuses (per level)
// -----------------------------------------------------------------------------

export const DEFENSE_STRUCTURE_BONUSES = {
  WALLS: { defensePercent: 5 },
  GUARD_TOWER: { attackPercent: 3 },
  WATCH_TOWER: { detectionRangePercent: 10 },
  BALLISTA: { attackVsLargePercent: 8 },
} as const;

// -----------------------------------------------------------------------------
// 16. Arcana Costs (gold + mana)
// -----------------------------------------------------------------------------

export const ARCANA_COSTS = {
  TIER_1: { mana: 500, gold: 1000, timeSeconds: 10 * 60 },
  TIER_2: { mana: 1500, gold: 3000, timeSeconds: 25 * 60 },
  TIER_3: { mana: 4000, gold: 7000, timeSeconds: 45 * 60 },
  TIER_4: { mana: 8000, gold: 15000, timeSeconds: 75 * 60 },
  DRAGON: { mana: 25000, gold: 40000, timeSeconds: 180 * 60 },
} as const;

// -----------------------------------------------------------------------------
// 17. Building Build Times & Costs (initial construction)
// -----------------------------------------------------------------------------

export const BUILDING_BUILD_TIMES = {
  SAWMILL: 30,
  FARM: 1 * 60,
  MINE: 2 * 60,
  OBSERVATORY: 3 * 60,
  BARRACKS: 2 * 60,
  STORAGE: 1 * 60,
} as const;

export const BUILDING_BUILD_COSTS: Record<string, { ore?: number; provisions?: number; gold?: number; lumber?: number }> = {
  SAWMILL: { lumber: 50, ore: 30 },
  FARM: { lumber: 80, ore: 30 },
  MINE: { lumber: 100, ore: 50 },
  OBSERVATORY: { lumber: 150, ore: 50, gold: 50 },
  BARRACKS: { lumber: 120, ore: 80 },
  STORAGE: { lumber: 60, ore: 40 },
} as const;

// -----------------------------------------------------------------------------
// 18. Storage Caps by Level
// -----------------------------------------------------------------------------

export const STORAGE_CAPS_BY_LEVEL = {
  1: 5000,
  2: 10000,
  3: 20000,
  4: 40000,
  5: 75000,
} as const;

// -----------------------------------------------------------------------------
// 19. Tutorial Steps
// -----------------------------------------------------------------------------

export const TUTORIAL_STEPS = {
  START: 0,
  BUILD_SAWMILL: 1,
  BUILD_FARM: 2,
  BUILD_MINE: 3,
  BUILD_OBSERVATORY: 4,
  RESEARCH_IRRIGATION: 5,
  BUILD_BARRACKS: 6,
  TRAIN_INFANTRY: 7,
  NPC_RAID: 8,
  RAID_WON: 9,
  UNLOCK_SCOUTS: 10,
  SCOUT_HIDEOUT: 11,
  ATTACK_HIDEOUT: 12,
  HIDEOUT_DESTROYED: 13,
  TUTORIAL_COMPLETE: 14,
} as const;

// -----------------------------------------------------------------------------
// 20. Storage Upgrade Costs (lumber + ore, no provisions)
// -----------------------------------------------------------------------------

export const STORAGE_UPGRADE_COSTS = {
  2: { lumber: 200, ore: 100, timeSeconds: 5 * 60 } as ResourceCost,
  3: { lumber: 500, ore: 300, timeSeconds: 15 * 60 } as ResourceCost,
  4: { lumber: 1200, ore: 700, timeSeconds: 30 * 60 } as ResourceCost,
  5: { lumber: 3000, ore: 1500, timeSeconds: 60 * 60 } as ResourceCost,
} as const;

// -----------------------------------------------------------------------------
// 21. Defense Upgrade Costs (per structure type, per level)
//     Lumber-primary construction
// -----------------------------------------------------------------------------

export const DEFENSE_UPGRADE_COSTS = {
  WALLS: {
    1: { lumber: 150, ore: 80, timeSeconds: 5 * 60 } as ResourceCost,
    2: { lumber: 350, ore: 200, timeSeconds: 10 * 60 } as ResourceCost,
    3: { lumber: 800, ore: 450, timeSeconds: 20 * 60 } as ResourceCost,
    4: { lumber: 1800, ore: 1000, timeSeconds: 40 * 60 } as ResourceCost,
    5: { lumber: 4000, ore: 2200, timeSeconds: 75 * 60 } as ResourceCost,
  },
  GUARD_TOWER: {
    1: { lumber: 200, ore: 100, gold: 80, timeSeconds: 5 * 60 } as ResourceCost,
    2: { lumber: 500, ore: 250, gold: 200, timeSeconds: 12 * 60 } as ResourceCost,
    3: { lumber: 1000, ore: 550, gold: 500, timeSeconds: 25 * 60 } as ResourceCost,
    4: { lumber: 2200, ore: 1200, gold: 1000, timeSeconds: 50 * 60 } as ResourceCost,
    5: { lumber: 4500, ore: 2500, gold: 2000, timeSeconds: 90 * 60 } as ResourceCost,
  },
  WATCH_TOWER: {
    1: { lumber: 100, ore: 60, gold: 40, timeSeconds: 3 * 60 } as ResourceCost,
    2: { lumber: 280, ore: 150, gold: 100, timeSeconds: 8 * 60 } as ResourceCost,
    3: { lumber: 600, ore: 350, gold: 250, timeSeconds: 18 * 60 } as ResourceCost,
    4: { lumber: 1400, ore: 750, gold: 600, timeSeconds: 35 * 60 } as ResourceCost,
    5: { lumber: 3000, ore: 1600, gold: 1300, timeSeconds: 65 * 60 } as ResourceCost,
  },
  BALLISTA: {
    1: { lumber: 350, ore: 200, gold: 150, timeSeconds: 8 * 60 } as ResourceCost,
    2: { lumber: 800, ore: 500, gold: 350, timeSeconds: 18 * 60 } as ResourceCost,
    3: { lumber: 1800, ore: 1100, gold: 800, timeSeconds: 35 * 60 } as ResourceCost,
    4: { lumber: 4000, ore: 2300, gold: 1700, timeSeconds: 60 * 60 } as ResourceCost,
    5: { lumber: 8000, ore: 4500, gold: 3500, timeSeconds: 100 * 60 } as ResourceCost,
  },
} as const;
